### ISSUE TITLE
Unable to create temporary file on Linux

### ISSUE THREAD

**Issue by lekeely** [nasa/DERT#1]
Trying to run LayerFactory (this is under Linux) I get the following error when I hit the "Apply" button:

./layerfactory 
java.io.IOException: Unable to create temporary file
at java.io.File.generateFile(File.java:1691)
at java.io.File.createTempFile0(File.java:1712)
at java.io.File.createTempFile(File.java:1839)
at gov.nasa.arc.dert.raster.geotiff.GTIF.loadNativeLibrary(GTIF.java:321)
at gov.nasa.arc.dert.raster.geotiff.GTIF.<clinit>(GTIF.java:311)
at gov.nasa.arc.dert.landscape.factory.RasterLayerPanel.applyPressed(RasterLayerPanel.java:352)
at gov.nasa.arc.dert.landscape.factory.LayerFactory.applyPressed(LayerFactory.java:378)
at gov.nasa.arc.dert.landscape.factory.LayerFactory$3.actionPerformed(LayerFactory.java:207)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1995)
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2318)
at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
at java.awt.Component.processMouseEvent(Component.java:6329)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
at java.awt.Component.processEvent(Component.java:6094)
at java.awt.Container.processEvent(Container.java:2040)
at java.awt.Component.dispatchEventImpl(Component.java:4692)
at java.awt.Container.dispatchEventImpl(Container.java:2098)
at java.awt.Component.dispatchEvent(Component.java:4520)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4574)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4235)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4165)
at java.awt.Container.dispatchEventImpl(Container.java:2084)
at java.awt.Window.dispatchEventImpl(Window.java:2492)
at java.awt.Component.dispatchEvent(Component.java:4520)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:681)
at java.awt.EventQueue.access$400(EventQueue.java:81)
at java.awt.EventQueue$2.run(EventQueue.java:640)
at java.awt.EventQueue$2.run(EventQueue.java:638)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:58)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:68)
at java.awt.EventQueue$3.run(EventQueue.java:654)
at java.awt.EventQueue$3.run(EventQueue.java:652)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:58)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:651)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Exception in thread "Thread-2" java.lang.UnsatisfiedLinkError: gov.nasa.arc.dert.raster.geotiff.GTIF.openTIFF(Ljava/lang/String;Ljava/lang/String;)J
at gov.nasa.arc.dert.raster.geotiff.GTIF.openTIFF(Native Method)
at gov.nasa.arc.dert.raster.geotiff.GTIF.open(GTIF.java:356)
at gov.nasa.arc.dert.landscape.factory.RasterPyramidLayerFactory.buildPyramid(RasterPyramidLayerFactory.java:91)
at gov.nasa.arc.dert.landscape.factory.RasterLayerPanel.run(RasterLayerPanel.java:365)
at gov.nasa.arc.dert.landscape.factory.LayerFactory$4.run(LayerFactory.java:386)
at java.lang.Thread.run(Thread.java:682)

**Comment by ggdio** [comment]
Hello,
May I contribute to this project and help you guys to fix this problem ?

[~Dio](http://guilhermedio.com)

**Comment by lekeely** [comment]
This issue is mainly concerned with Java 1.6. As of release 1.0b4, Java 1.6 is no longer supported by DERT. Thank you ggdio, for your kind offer.
