### ISSUE TITLE
supporting JPEG compressed grayscale image in layerfactory

### ISSUE THREAD

**Issue by AndrewAnnex** [nasa/DERT#6]
Although not a blocker-issue for me, I just tried to use a JPEG compressed 8bit geotiff (I used the `-co COMPRESS=JPEG` flag to create the 8bit image with gdal_translate) with layerfactory and ran into the following error and stack trace:
```
TIFFReadDirectory: Warning, Unknown field with tag 347 (0x15b) encountered.
Writing temporary 33152 x 65920 file
java.lang.IllegalStateException:  compression support is not configured
        at gov.nasa.arc.dert.raster.geotiff.GTIF.computeMinMaxFromTile(GTIF.java:1819)
        at gov.nasa.arc.dert.raster.geotiff.GTIF.loadGray(GTIF.java:1542)
        at gov.nasa.arc.dert.landscape.factory.RasterPyramidLayerFactory.loadRasterFile(RasterPyramidLayerFactory.$
ava:406)
        at gov.nasa.arc.dert.landscape.factory.RasterPyramidLayerFactory.createPaddedRaster(RasterPyramidLayerFacto
ry.java:330)
        at gov.nasa.arc.dert.landscape.factory.RasterPyramidLayerFactory.buildPyramid(RasterPyramidLayerFactory.jav
a:157)
        at gov.nasa.arc.dert.landscape.factory.LayerFactory.createLayer(LayerFactory.java:171)
        at gov.nasa.arc.dert.landscape.factory.LayerFactory.main(LayerFactory.java:103)
```

**Comment by lekeely** [comment]
This should be fixed now in the latest (1.0.3) release.
